### ISSUE TITLE
Override whitelist when a third party links to multiple first parties

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#100]
A paraphrased example from @jonathanKingston:

Say you have two sites that both link to google-analytics.com:
1. google.com (owns google-analytics.com)
2. example.com (does not own google-analytics.com)

Initially, say you have only loaded google.com, the graph should only display the first party node for google.com, not the google-analytics.com third party node, since google-analytics.com is owned by google.com (i.e. google-analytics.com is whitelisted per #98 ).

When you visit example.com next, currently the graph would only show the link between example.com and google-analytics.com. There would not be a link between google.com and google-analytics.com due to the whitelist check. We should override this to display this link in this instance.

To put it more generally, if a previously whitelisted third party later links to one or more first parties for which it is not whitelisted, the previously ignored link between the whitelisted first and third party should be added.

In addition to adding more transparency around the prevalence of a particular third party site, this has the added benefit of connecting two subgraphs, which can help keep the visualization more contained to the graph area in the UI (Issue #76).

@jonathanKingston Could you please elaborate on how this could be done, and what it might take implementation-wise?
@groovecoder Do you know why some hostnames in the [Disconnect Entity List](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-entitylist.json) have the `www` subdomain and others don't?

**Comment by jonathanKingston** [comment]
This highlights the issue very well, to follow with a little further guidance on how to make this so.

**Comment by groovecoder** [comment]
Ooo, I like this improvement.

I don't have a great answer why some hostnames include `www.` and some do not. 😢 It's likely that some entities simply serve their properties and resources from the 2 separate domains.

**Comment by jonathanKingston** [comment]
From memory the chosen solution in capture was to tag the websites as `possiblyIgnorable` which the store.js code will decide if it should send out the nodes based on the links that come from this third party.

- If the third party being stored is `possiblyIgnorable` and only has a first party that we want to ignore then don't send updates.
- If the user loads the page with entities with `possiblyIgnorable` flag, don't draw unless they have a first party link not in the list
- When the third party is updated with the links to another first party send out the update.

If we can design it so that store doesn't need to know about the list that would be great. Perhaps possibly ignorable could be the list of firstParties?

**Comment by biancadanforth** [comment]
I have some pseudocode that I am working on implementing; this pseudocode builds on top of [this PR](https://github.com/electrolyfish/lightbeam-we/pull/106) (which will hopefully be merged soon) for adding the whitelist.

@jonathanKingston would be great to get some initial feedback from you if this seems like a good direction.

*Pseudocode*
Basically in `capture.js`, take my `onWhitelist` method (returns true if the third party is whitelisted) and put it inside the `sendThirdParty` method; whitelisted data gets set aside into an `ignoreList` object while regular data gets passed onto store via `store.setThirdParty`; if the regular data includes a third party in the `ignoreList`, then that data gets plucked out of the `ignoreList` with its own `store.setThirdParty` call.

**Comment by jonathanKingston** [comment]
@biancadanforth this won't work as the user might restart the browser between loading a whitelisted page and loading the same third party on a page we care about, we will need to store these.

This is why I was suggesting that `sendThirdParty` would be passed some an array of ignorables for that third party.

So:

- google.com loads googleanalytics.com
- store recives:
```
      const data = {
        document: "https://google.com",
        ignorables: ["abc.xyz", "google.com"....]
        ....
        requestTime: 234234234234
      };
      store.setThirdParty(
        "https://google.com",
        "https://googleanalytics.com",
        data);
```
- store only emits third parties that have links outside of the ignorables list
  - store doesn't know about the full list or the parsing logic
  - capture doesn't know about the links currently held by the third party

**Comment by jonathanKingston** [comment]
We could also move all the logic into store perhaps, we will want to share the domain matching logic perhaps. (This can easily be in a util.js also)

**Comment by biancadanforth** [comment]
So @jonathanKingston , the whitelist check inside `capture.sendThirdParty` would populate the `data[ignorables]` array for that third party (and perhaps flag it as ignored with a separate `isIgnored` boolean to tell us what its current ignore status is?)... what about something like this?:

```javascript
const data = {
  document: "https://google.com",
  ignorables: ["abc.xyz", "google.com"....]
  isIgnored: true,
  requestTime: 234234234234
};
store.setThirdParty(
  "https://google.com",
  "https://googleanalytics.com",
  data);
```

... and `store.sendThirdParty` would check if the first party is in the `data[ignorables]` and if `isIgnored` is true or false.

```javascript
inside store.setThirdParty...
if ((!data[ignorables].has(firstParty)) {
  if (data[isIgnored])) {
    data[isIgnored] = false;
    // perform standard third party checks/config of this._websites[thirdParty]
    // and call store.updateChild if new
  }
```

**Comment by jonathanKingston** [comment]
`isIgnored` is just duplicating half a check, I don't think we need that.

> boolean to tell us what its current ignore status is

Only store will know the true answer to this, otherwise we will be making capture query store first. We are pushing a third party to the store, the capture code doesn't know the current state of that website in the store. So it might be that google analytics has been seen on multiple sites already.
`isIgnored` could be stored in the store side of the code to reduce the time seeing if it matched on the list.
- When the store sees an `ignorables` array we check in store if the third party has already been seen outside of that list, if it hasn't we check the list of first parties listed there.

util.js
```
const utils = {
  checkHostnameInList(hostname, list) {
    const vars = this.getHostnameVariants(hostname);
    // check vars is not in list.
    return isInList;
  },
  getHostnameVariants() {
  }
}
```

**Comment by jonathanKingston** [comment]
Give me a second, I'm re-thinking yet again.

**Comment by jonathanKingston** [comment]
Further brain dump from previous meeting:

As discussed this whitelist work will move to store.js and capture will continue to be stateless.
We agreed the stored website object having a boolean to represent if a site has been seen on a non whitelist first party. This means store will skip the stages of looking through the whitelist at all when it has.

The state will be captured of if it's ignorable. Currently I don't think we have the same 3rd party under two 1sts however that could change with generic domains, we either need to be **careful** not to fall into that trap or have a unset state for this variable we spoke about. Ideally in future we might have something like indexed db lookup if the third party ever exists before checking the first that way we can always store the state to check/not check in future.
