### ISSUE TITLE
Structure of store object

### ISSUE THREAD

**Issue by princiya** [electrolyfish/lightbeam-we#15]
Based on our slack discussions, this is the proposed structure for the store object:
```
websites: {
    'website.com': {
      faviconUrl: '/link/to/url',
      firstAccess: date,
      lastAccess: date,
      thirdPartyRequests: {
        'a.com': {
          requestTime: date,
          cookies: []
        },
        'b.com': {}
        'c.com': {}
      }
    }
 }
```

**Comment by biancadanforth** [comment]
Thanks! @princiya, @jkt I believe we also discussed not capturing cookies as part of the MVP? Looking at slack history.

**Comment by biancadanforth** [comment]
I have removed cookies, replacing it with a new key `additionalRequests`. This key indicates any requests a third party makes to additional third parties. For example, when visiting youtube.com, doubleclick.net makes an additional request to 2mdn.net.
```javascript
websites: {
    'website.com': {
      faviconUrl: '/link/to/url',
      firstAccess: date,
      lastAccess: date,
      thirdPartyRequests: {
        'a.com': {
          requestTime: date,
          additionalRequests: []
        },
        'b.com': {}
        'c.com': {}
      }
    }
 }
```

**Comment by biancadanforth** [comment]
I have removed `cookies` and added a `loadedBy` key to show additional requests made by third parties as the originUrl.

```javascript
websites: {
  'website.com': {
    faviconUrl: '/link/to/url',
    firstAccess: date,
    lastAccess: date,
    thirdPartyRequests: {
      'doubleclick.net': {
        requestTime: date,
      },
      '2mdn.net': {
        requestTime: date,
        loadedBy: 'doubleclick.net'
      },
      'b.com': {},
      'c.com': {}
    }
  }
 }
```

**Comment by jonathanKingston** [comment]
It might not have been clear on this.

In https://github.com/electrolyfish/lightbeam-we/issues/7#issuecomment-303249670 I mentioned that the capture should be isolated from the storage code.

I'm also not exactly worried about how we store these right now. We can probably aggregate data sent to the storage object under "hostname" for both for first party and third party requests. This aggregating of the data could be done inside the storage code or the collation of the data code (for now it doesn't matter if storage receives hostnames or url).

First access and last access, should be implemented in the storage code based upon an access time passed to the request. The collation code shouldn't keep state of existing requests really.

How we actually store to the the browser storage API isn't important either, we should be thinking about the API for the storage object we are making. Let's concentrate on having two methods exposed by the storage object @princiya is working on `firstPartyRequest` and `thirdPartyRequest`

```
storage.firstParty(tab.url, {
  faviconUrl: "/link/to/url",
  access: 
});

storage.thirdPartyRequest(tab.url, {
  document: options.documentUrl,
  target: options.url,
  origin: options.originUrl,
  cookieStoreId: tab.cookieStoreId.
  requestTime: timestamp
});
```

@princiya can then decide on the best way to store this in the simplest manner for now (how we store should likely be formed from the API to query the data).

Query methods on storage will likely be:
```
storage.getFirstParties();
// {"blah.com": {favIconUrl: "/thing", lastRequestTime: 31232321323, firstRequestTime: 321321321331}, "other.com": {favIconUrl: "/thing", lastRequestTime: 31232321323, firstRequestTime: 321321321331}}
storage.getFirstParty("blah.com");
// {favIconUrl: "/thing", lastRequestTime: 31232321323, firstRequestTime: 321321321331}
storage.getThirdParties("blah.com");
// {"thing.com": {favIconUrl: "/thing", lastRequestTime: 31232321323, firstRequestTime: 321321321331}}
```
