### ISSUE TITLE
Storage object: set method

### ISSUE THREAD

**Issue by princiya** [electrolyfish/lightbeam-we#18]
In `browser.storage.local.set(keys)` method, the `keys` param is:
```
An object containing one or more key/value pairs to be stored in storage. If an item already exists, its value will be updated.
```
Our store structure looks like the following: #15 
```
websites: {
 'a.com': {},
 'b.com': {}
}
```
When we call `set()` to add/update hostnames, we need to pass the whole `websites` object. `websites` will be the key to the `browser.storage.set()`.
We need to update the local `websites` object with the right logic to add/update etc.

@jkt open for discussions, before I proceed :)

**Comment by jonathanKingston** [comment]
We just need to make sure whatever `set` does `get` behaves the same way. Like I think some of the other code treats this as "set single item" where as `get` is "get all".

We might want to use `_` prefix for internal methods to this object as the concept of private isn't really possible just "out of scope" which isn't really the same. [There are proposals for the future on this though](https://github.com/tc39/proposal-private-fields).

Storing `websites` as a local object is fine, however I would keep it stored as often as possible. Store can keep a local copy to account for async issues later (fast calling store will break, fine as a follow up though)

Perhaps `_store` and `_read` make more sense for interacting with the browser itself.

So perhaps (untested totally):
```
{
  init() {
    // On reloading the browser use the store
    const data = await browser.storage.local.get(["websites"]);
    this.websites = data.websites || null;
  },
  async _store(websites) {
    // Local cache of the data to prevent async issues
    this.websites = websites;
    // Store to the browser for extension restore, returns when data is stored.
    return browser.storage.local.set({websites});
  },
  _read() {
    return this.websites;
  },
  async setFirstParty(domain, data) {
    const websites = this._read();
    websites[domain] = data;
    this._store(websites);
  },
  ...
}
```

**Comment by princiya** [comment]
How about `_write()` instead of `_store()`?

**Comment by jonathanKingston** [comment]
Sure!
