### ISSUE TITLE
UR/UX 

### ISSUE THREAD

**Issue by princiya** [electrolyfish/lightbeam-we#20]
From slack discussions, here are @jkt 's questions:

1. Ask about UX of how to express tracking
2. Use "boxes" as a notation and suggest if they could put some sites that link to "Lots" of websites in a "box" would that help understand?

More questions to be added through discussions!

**Comment by biancadanforth** [comment]
Those are good questions princiya. I just read this article about [asking good questions in UR](https://medium.com/user-research/never-ask-what-they-want-3-better-questions-to-ask-in-user-interviews-aeddd2a2101e).

Hoping to learn more from groovecoder about his audience in our meeting today, since that may help us to better frame the questions too.

Here are some of my ideas for possible questions:
- What brought you to this class today?
- Have you ever used a tool like Lightbeam before? If so, please list.
- If you had to summarize what Lightbeam does, what would you say?
- Was there anything today that you found especially valuable?
- Was there anything today that you found especially confusing?
- Are you concerned about online privacy? If so, what concerns you?
- Is there anything about online privacy you would like to know more about?

**Comment by princiya** [comment]
@biancadanforth Those are @jkt 's questions :) I made a note of them from slack.

**Comment by biancadanforth** [comment]
I haven't been on slack, so I guess great minds think alike!

**Comment by jonathanKingston** [comment]
- How would using lightbeam change your use of the internet?
- How would you save yourself from the evils?

**Comment by princiya** [comment]
- Would you recommend Lightbeam to others?

**Comment by groovecoder** [comment]
From [the Mozilla Privacy Basics Lightbeam class](https://chadsansing.github.io/curriculum-testing/expanded-privacy-curriculum/tracking-cookies.html):
Before Lightbeam:
* Is all tracking bad?
* Can you think of an instance when you're ok with sharing your data?
* What kind of organizations do you think might already be tracking you across the Web?

After Lightbeam:
* How would you explain the idea of cookies and tracking to someone else?
* Can cookies ever be useful to you, the user?
* Are the some websites that you think are okay to track you? Are there others you don't want to have following you around the Web?
* What habits can you develop - and what strategies and tools can you use - to prevent yourself from being followed online?

There's also [a cool behavior model for persuasive design](http://www.bjfogg.com/fbm_files/page4_1.pdf) that deep-dives into peoples' motivation and ability to change their (online) behavior.

**Comment by biancadanforth** [comment]
Here's what we seemed to converge on from our meeting:

- Have you ever used a tool like Lightbeam before? If so, please list.
- If you had to summarize what Lightbeam does, what would you say?
- Was there anything that you found especially valuable? Especially confusing?
- Would you use Lightbeam again?
- (from Mozilla class @groovecoder posted above) What habits can you develop - and what strategies and tools can you use - to prevent yourself from being followed online?
- How might you learn more about online privacy? What would you search for?

**Comment by groovecoder** [comment]
ooo, I just started this paper which seems very relevant to Lightbeam? http://delivery.acm.org/10.1145/2900000/2892413/ea2837-gambino.pdf?ip=68.0.123.163&id=2892413&acc=CHORUS&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E6D218144511F3437&CFID=940430111&CFTOKEN=89342189&__acm__=1495662231_f368be1ddae185122755a0c040c3da02

**Comment by groovecoder** [comment]
FTA, to @jonathanKingston's question about "containing" or "boxing-in" trackers ...

> Bubble Heuristic 
> Features such as incognito or private web-browser 
> modes, as well as carrying out transactions on one’s 
> home network engendered a sense of safety. One 
> participant shared, “
> I never really thought I shouldn’t 
> be emailing on my cell phone, but I do feel better if I’m 
> at home and it’s my tablet or my cell phone and it’s on 
> my wi-fi because it’s secure and nobody presumably 
> could easily break into it
> .” Similarly, another participant 
> shared a willingness to disclose some personal 
> information at home but not over public networks or 
> unknown connections such as at a hotel, adding “
> Yea so 
> I just kind of am in my own little box [on my own 
> network]
> .” Indeed research has shown that users tend 
> to have a strong faith in personal wi-fi networks and 
> private browsing modes despite the presence of actual 
> privacy and security risks [7, 9]. Psychologically, the 
> bubble heuristic
>  represents additional security when 
> individuals feel that they are in an online ‘enclosure’ of 
> some sort, be it a home network, a virtual private 
> network, or a ‘virtual ma
> sk’ such as what may be 
> provided by incognito mode.   

So I guess we should re-name "Containers" to "Bubbles" ?

**Comment by biancadanforth** [comment]
@groovecoder : Great article! It kind of had a 'holier-than-thou' tone, which I found amusing. :) Here are some of my take-aways that we could apply to the Lightbeam UI:
- Nudges in the form of visual cues (ex: password strength meter, the lock icon next to the website URL to indicate a valid security certificate) have been shown to result in improved privacy behavior. If we do provide actions users can take inside Lightbeam, they could be accompanied by recognizable icons like a lock.
- If people think the information disappears, they are more likely to share it. Keep the option to clear all data in Lightbeam, and make that button prominent on the UI.
- Lightbeam leverages this common sentiment: my information may be shared with third-parties, therefore it is unsafe. But perhaps we can use a visual cue to indicate the relative risk of different third-parties. A lot to explore here.
- Many people feel more comfortable if their information is not stored in what they perceive to be a permanent fashion: We could remove this fear by notifying users their browsing history is only stored locally (not sent anywhere else).

I wish the article made more of a connection between each of their _heuristics_ and a specific interface cue. Really interesting (and short!) article. Thanks for sharing!

**Comment by groovecoder** [comment]
Here's a .zip of the feedback sheets people filled out after the Lightbeam class @ the library.

[lightbeamfeedback.zip](https://github.com/electrolyfish/lightbeam-we/files/1032902/lightbeamfeedback.zip)

**Comment by jonathanKingston** [comment]
Closing this as I think we got the feedback we wanted. If we want to run this again etc we can create another issue etc.
