### ISSUE TITLE
Consider improving README.md

### ISSUE THREAD

**Issue by groovecoder** [electrolyfish/lightbeam-we#21]
I'm personally a fan of [README-driven-development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html).

**Comment by princiya** [comment]
yes i wanted this one too. then thought maybe we do this after the MVP?! :)

and the issue should be title, not 'improving'. 'writing' one instead ;)

**Comment by princiya** [comment]
@jonathanKingston @groovecoder @biancadanforth which license do we mention in the readme?

**Comment by biancadanforth** [comment]
@princiya I don't know too much about licensing, but I did check the original Lightbeam repo [license](https://github.com/mozilla/lightbeam/blob/master/LICENSE), and that uses Mozilla Public License 2.0.
