### ISSUE TITLE
Addon deleted on AMO

### ISSUE THREAD

**Issue by Booteille** [electrolyfish/lightbeam-we#260]
Hi.

I am wondering why this addon is no longer accessible on AMO.

Thanks.

**Comment by princiya** [comment]
Interesting.. I just realised now that it's been deleted! No idea why this happened 😞

**Comment by Booteille** [comment]
Yeah, I just noticed it too...

I hope it's just a mistake. It's a great tool to use when we want to advocate in favor of privacy.

**Comment by petethomas** [comment]
Looking in the Internet Archive it seems the addon was [available up until Sept 21 ](https://web.archive.org/web/20190921130026/https://addons.mozilla.org/en-US/firefox/addon/lightbeam/) but offline as of [Sept 28](https://web.archive.org/web/20190921130026/https://addons.mozilla.org/en-US/firefox/addon/lightbeam/).

**Comment by princiya** [comment]
I spoke to folks from Mozilla, they said they decided to remove from AMO because it is no longer actively maintained 😞

**Comment by Forceflow** [comment]
But was the version up on AMO still working?

I just tried to use the extension via about: debugging, and on both my Ubuntu and Windows machines it's just displaying a black screen where the graph should be. Lots of errors in the JS debug console.

**Comment by princiya** [comment]
Yes, the extension has been working. Which version of Firefox did you try? @Forceflow

**Comment by Forceflow** [comment]
I'm on 69.0.2 (64-bit) and following the following steps:

1. Download source code
2. Open about:debugging
3. Loading temporary extension using the manifest.json
4. Open lightbeam
5. Browse to a site in other tab
6. Observe lightbeam (no results, buttons not working, errors in JS console)

I've also tried it using web-ext from NPM - with the same result.

**Comment by facyber** [comment]
Hello,

I would like to report the same issue.

Firefox 69.0.2 (64-bit) on Linux.

**Comment by Forceflow** [comment]
I've got a report from someone who installed the extension from AMO when it was still up, and her version is still working fine.

So I think either the AMO version and this repo are out of sync, or the "temporary add-on" method of using this extension has stopped working.

**Comment by eviljeff** [comment]
https://support.mozilla.org/en-US/kb/lightbeam-extension-firefox-no-longer-supported

(I'm just posting the link; I'm not otherwise involved)

**Comment by Forceflow** [comment]
Okay - I should probably open a new issue for the current repo build being broken / not working.

**Comment by lazerhawk** [comment]
Well, if it's no longer being maintained by Mozilla, how will pull requests/bug fixes be handled now? Even if the tracking research is done, the visualization still has value on its own.

**Comment by Forceflow** [comment]
I don't know. Someone should probably fork this, although it would be nice to get some sort of green light from Mozilla.

**Comment by princiya** [comment]
I am trying to re-upload Lightbeam, I will keep you all posted here.

**Comment by princiya** [comment]
Lightbeam is re-uploaded https://addons.mozilla.org/en-US/firefox/addon/lightbeam-3-0/

**Comment by princiya** [comment]
@Forceflow regarding your previous comment, if you tried to install Lightbeam via the latest code on Github repository, then it shows a black screen, I have similar problems too.
I had to clean up the code a bit, I will push the latest code here later today https://github.com/princiya/lightbeam-we

**Comment by RokeJulianLockhart** [comment]
> [`#issuecomment-552402852`](https://github.com/mozilla/lightbeam-we/issues/260#issuecomment-552402852)

@princiya, [`addons.mozilla.org/en-US/firefox/addon/lightbeam-3-0`](https://addons.mozilla.org/en-US/firefox/addon/lightbeam-3-0/) is not, currently, available.

**Comment by princiya** [comment]
Yes, it's been disabled last week. The AMO team wanted some security-related answers and I was not available during the year-end holidays. I will get back to them this month.

**Comment by Booteille** [comment]
Oh shit. I had a privacy workshop next weekend and needed Lightbeam to show how trackers are everywhere.

I will try to install it manually.

Thanks for your work, princiya!

Edit: Btw, since I got an answer to my question, and Lightbeam 3.0 is a thing, I close the issue.
