### ISSUE TITLE
Decide which assertion library style to use and enforce

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#33]
@princiya has made an initial test set-up #23 using the _Expect_ BDD style, while @jkt expresses his strong preference for the _Assert_ style. We should choose a [style ](http://chaijs.com/guide/styles/) to use and enforce it via ESLint.

From our slack discussion thus far, jkt says _Should_ is dangerous since it modifies the object prototype with a `should` property and _Expect_ is not truly BDD like [Cucumber](https://en.wikipedia.org/wiki/Cucumber_(software)#Features.2C_Scenarios.2C_and_Steps).

**Comment by princiya** [comment]
Thanks for creating this issue @biancadanforth 

Honestly, I have used `expect` by fluke. I only felt `should` wasn't appropriate, but was clearly not sure about the differences between `expect` and `assert`. Thanks @jkt for the brief summary.

I will create a PR and let's stick to `assert`

**Comment by biancadanforth** [comment]
Great thanks @princiya. I will use `assert` for my tests as well then!
