### ISSUE TITLE
Add git hook - `husky`

### ISSUE THREAD

**Issue by princiya** [electrolyfish/lightbeam-we#34]
It is easy to forget to run linting or test tasks before committing or pushing code and this can result in a broken build.

A way to work around the above problem is to use git hooks and I suggest to use `husky`.

Open for discussions :)

**Comment by jonathanKingston** [comment]
Seems good to me, never used it but jQuery is on the tin etc and probably super lightweight package. @biancadanforth are you good with this?

**Comment by biancadanforth** [comment]
@princiya, @jkt: Seems like a good idea, but I'd like to make sure I understand things...

I looked a bit at husky's [documentation](https://github.com/typicode/husky) - looks like it basically calls ~`npm test` at various stages of the git commit/PR process--and for us those stages are pre-commit for eslint test and pre-push for all tests? Perhaps I don't fully understand, but doesn't Travis do something similar to a pre-push git hook? How do the two interact?

**Comment by princiya** [comment]
@biancadanforth Travis is post-push. Travis ensures the whole build is continuously integrated. Travis also comes with test coverage reports etc, (We need to do this next).
Husky is for us (developers) to make sure we don't push bad code.
@jonathanKingston correct me :)

**Comment by biancadanforth** [comment]
Well, @princiya I think husky sounds like a good idea. Not sure exactly how it works, but I guess I'll find that out on my next PR!

**Comment by princiya** [comment]
To test it out, break some eslint rules and try to commit your code, it fails. Break some tests and try to push your code, it fails! @biancadanforth

**Comment by princiya** [comment]
@biancadanforth taking the last shot in convincing you :) let's see, if this works.

husky is client side, travis is server side. 

what I mean from the above statement is, developers can remove/disable husky from their package.json, checkin some untested/unlinted code. But Travis catches this and fails the build.

**Comment by biancadanforth** [comment]
Okay thanks @princiya for that clarification. I will try it out shortly!
