### ISSUE TITLE
Remove any global off ESLint comments

### ISSUE THREAD

**Issue by jonathanKingston** [electrolyfish/lightbeam-we#45]
Comments like: https://github.com/electrolyfish/lightbeam-we/blob/master/js/capture.js#L1
Should be removed, in favour fixed to not be required. If this isn't possible then disable just one line not the entire file.

For example: `// eslint-disable-next-line no-unused-vars`

However the "classes" can be turned into globals within ESLint `eslint.json` preventing the need for some of these.

```
"globals": {
  "browser": true,
  "myStorageObjectName": true,
  "myCaptureObjectName": true
},
```

**Comment by biancadanforth** [comment]
@jonathanKingston ; I believe PR#43 closes this; but correct me if I am wrong?

**Comment by princiya** [comment]
This has been fixed :). @jonathanKingston @biancadanforth
