### ISSUE TITLE
Header fixes for small screens

### ISSUE THREAD

**Issue by jonathanKingston** [electrolyfish/lightbeam-we#56]
This isn't about implementing a full responsive layout that can come later.

However on smaller screens some of the text wrapping causes layout issues:

![selection_692](https://user-images.githubusercontent.com/338988/27222958-5626e324-5286-11e7-9036-7ffc18ab1916.png)

The HTML for this top bar is also:
```
<section class="top-bar">
        <div>
          <span>
            <h2>Data Gathered Since</h2>
            <!-- @todo get date-start from store -->
            <h3 id="date-start">June 13, 2017</h3>
          </span>
          <span>
            <h2>You Have Visited</h2>
            <!-- @todo get num-sites-visited from store -->
            <h3><span id="num-sites-visited">6</span> Sites</h3>
          </span>
          <span>
            <h2>You Have Connected With</h2>
            <!-- @todo get num-third-parties from store -->
            <h3><span id="num-third-parties">16</span> Third Party Sites</h3>
          </span>
        </div>
        <!-- @todo add tracking protection and toggle functionality -->
        <div class="tracking-protection">
          <h2>Tracking Protection</h2>
          <div class="toggle-outer">
            <div class="toggle-inner">
            </div>
            <!-- @todo toggle-label to reflect state of tracking protection -->
            <div class="toggle-label">
            Off
            </div>
          </div>
        </div>
      </section>
```

I'm fairly convinced with grid this could be:
```
<section id="top-bar">
  <dl class="info-headings">
    <dt>
       Data Gathered Since
    </dt>
    <dd id="date-start">
      <time datetime="2017-06-13T11:00">June 13, 2017</time>
    </dd>

    <dt>
       You Have Visited
    </dt>
    <dd>
       <var id="num-sites-visited">6</var> Sites
    </dd>

    <dt>
      You Have Connected With
    </dt>
    <dd>
       <var id="num-third-parties">16</var> Third Party Sites
     </dd>
  </dl>

  <div class="tracking-protection">
    <label for="tracking-protection-control">Tracking Protection</label>
    <div class="toggle-switch"><input type="checkbox" id="tracking-protection-control" /></div>
  </div>
</section>
```

Comments:

- Using span's for block like items is usually a bad sign as they are an inline element by default so using div's is slightly better
- Now we have grid using dl's is certainly much easier for this use-case
- Using a real input element and using before means we get some of the accessibility goodness from the browser
- Using grid here should let it expand downwards and also later be reorganisable for mobile.
- I used var and time for a little bit of semantic goodness
- I can also see that flex could also be a good fit here, standards people just made it ok to wrap `<dd>` and `<dt>` with a `<div>` whatever works :)

**Comment by biancadanforth** [comment]
@jonathanKingston Thanks for the suggestion. Lots of new (to me) HTML elements to learn about.

```html
<dt>
  Data Gathered Since
</dt>
  <dd id="date-start">
    <time datetime="2017-06-13T11:00">June 13, 2017</time>
  </dd>
  <!-- ... -->
```
Why are we using `<time>` here instead of `<var>`, since we are pulling the date value from the store ultimately?

Also, regarding the tracking protection toggle switch: I updated it to use an `<input>` and `<label>` element, but to have a customized switch (that is still coupled to the checkbox via JS), I still ended up using span elements. I think the nitty gritty details of this can be a separate issue (e.g. implement the tracking protection toggle switch); what do you think?

**Comment by jonathanKingston** [comment]
> Why are we using <time> here instead of <var>, since we are pulling the date value from the store ultimately?

Because time means more semantically.

>  but to have a customized switch (that is still coupled to the checkbox via JS)

It should be possible with the right nesting and pseudo selectors in CSS using `:checked` and perhaps sibling selectors `input::checked + div` and perhaps pseudo elements like `::before` and `::after`.

> What do you think?

That sounds OK too, I haven't thought about it much but I suspect min-width isn't needed but not sure.

**Comment by biancadanforth** [comment]
> That sounds OK too, I haven't thought about it much but I suspect min-width isn't needed but not sure.

`min-width` is not needed ultimately; it's just a temporary way to prevent the header from breaking as you narrow the screen until a more comprehensive, responsive layout is made (which I am happy to take a stab at in the near future!).
