### ISSUE TITLE
UI/UX and other questions for previous Lightbeam developers

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#69]
Let's use this issue to share any questions we have in advance of our meeting(s) with the creators of the previous version of Lightbeam; here are some that I thought of:

- Did you perform any user testing on the existing Lightbeam, and if so, do you have the notes from those tests that you could share?
- What would you change and why?
- What would you keep and why?
- Did you do any studies (such as with Google Analytics) on what options were used most and how often tracking protection was used? If so, what did you discover?
- What is the icon at the very top right corner just in the graph view (dark area)? Looks like a globe. It appears to be disabled. It's the `<div class="toggle-site-profile">`.

**Comment by princiya** [comment]
- Why the name 'Lightbeam'?
- What is an interesting feature/piece of code you wrote for Lightbeam?
- Any challenges faced in code/architecture design?
- Lessons learned/advice for new developers?

- Visualisations being an integral feature, what was the thought process behind this?
- Performance related issues and steps taken/discussed?

**Comment by mmmavis** [comment]
> What is the icon at the very top right corner just in the graph view (dark area)? Looks like a globe. It appears to be disabled. It's the <div class="toggle-site-profile">

In case I forgot to share this gif tomorrow...

![lightbeam](https://user-images.githubusercontent.com/2896608/27362341-a9f01200-55e2-11e7-94bf-9200702e7788.gif)

Not sure this feature works for everyone as it doesn't work for @sabrinang.

**Comment by biancadanforth** [comment]
Link shared by Mavis Ou in slack, [Lightbeam Ted Talk](http://blog.ted.com/meet-collusion-announced-today-onstage-at-ted-u/).

Link shared by Sabrina Ng in slack, [Initial Lightbeam Design Research](http://research.ecuad.ca/lightbeam/).
