### ISSUE TITLE
Initial capture of data

### ISSUE THREAD

**Issue by jonathanKingston** [electrolyfish/lightbeam-we#7]
In #1 we set out to decide what is needed to capture.

In the MVP we should aim to have a class/object that can be setup to manage the communication with the browser then use the storage class.

**Comment by biancadanforth** [comment]
Based on a slack discussion, I am working on an object structured more or less like this to capture data:

```javascript
const websites = {
  "website.com": {
    faviconUrl: '/link/to/url',
    firstAccess: 123456677034,
    lastAccess: 123350694633,
    thirdPartyRequests: [
      'a.com',
      'b.com',
      'c.com'
    ]
  },
  // ...
};
```
Interestingly, when I visit youtube.com, among the many responses, I get an originUrl other than youtube.com (specifically, doubleclick.net) that itself makes a number of third party requests. @jonathanKingston, how should these requests be captured?

**Comment by jonathanKingston** [comment]
@biancadanforth it's likely that doubleclick scripts load more 3rd parties. Currently Lightbeam treats all of these requests as third parties to youtube.com however I think they log where it was loaded from.

From memory there are a few undocumented Firefox specific properties that give better answers to these questions. However I'm not sure how this would be ported to chrome. Can you dump out some example values from onBeforeRequest and other API calls?

**Comment by biancadanforth** [comment]
@jonathanKingston, for an `originUrl` of doubleclick.net and a `targetUrl` of 2mdn.net, the `response` object is:
```javascript
{ requestId: "383", url: "https://s0.2mdn.net/viewad/2992003/…", originUrl: "https://pubads.g.doubleclick.net/ga…", method: "GET", tabId: 1, type: "image", timeStamp: 1495475961750, frameId: 2147483692, parentFrameId: 0, fromCache: true, ... }
```
I am not making any other API calls at the moment.

**Comment by jonathanKingston** [comment]
https://github.com/jonathanKingston/extension-debugging/blob/master/third-party-logger/background.js#L48

**Comment by jonathanKingston** [comment]
As mentioned on slack, lets not over complicate the capturing stage.

```
storage.newFirstParty(tab.url, {
  faviconUrl: "/link/to/url",
  access: 
});

storage.thirdPartyRequest(tab.url, {
  document: options.documentUrl,
  target: options.url,
  origin: options.originUrl,
  cookieStoreId: tab.cookieStoreId.
  requestTime: timestamp
});
```

From my initial debugging [here](https://github.com/jonathanKingston/extension-debugging/blob/master/third-party-logger/background.js#L42) all those Urls are different sometimes different.

My understanding is:

- documentUrl: If the sub resource was loaded from a subframe
- url: the url being loaded itself
- origin: the origin the request has loaded from, so documentUrl or JS or CSS loading it
- tab.url: this is the clearest way to know what top level frame it loaded from.
