### ISSUE TITLE
Update visualization with a storage callback

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#75]
My earliest experiment with the D3 visualization library was using the setInterval code below to update the graph periodically with the latest values from storage:

```javascript
  // when data changes, update
  // @todo find a good way to listen for changes
  setInterval(async function() {
    websites = await storeChild.getAll();
    transformedData = transformData(websites);
    const nodesNext = transformedData.nodes;
    const linksNext = transformedData.links;

    if (nodesNext.length !== nodesPrev.length
      || linksNext.length !== linksPrev.length) {
      viz.update(nodesNext, linksNext);
      nodesPrev = nodesNext;
      linksPrev = linksNext;
    }
  }, 3000);
```
We should provide a callback function for storage to pass to `lightbeam.js` to draw the new state of `websites` when its value changes. @jonathanKingston can you please elaborate on how this might take shape?

**Comment by jonathanKingston** [comment]
Super pseudo code... 

Store:
```
{
  ports: new Set(),
  init() {
    browser.runtime.onConnect.addListener((port) => {
      this.ports.add(port);
    });
  },
  notifyPorts(methodName, updateData) {
    this.ports.forEach((port) => {
      port.postMessage({
        methodName
        updateData
      });
    });
  },
  setFirstParty(hostname, thing) {
    // some stuff
    const updatedData = {
      hostname,
      thing
    };
    this.notifyPorts("setFirstParty", updatedData);
  }
}
```

StoreChild
```
{
  this.callbacks: new Set(),
  init() {
    this.port = browser.runtime.connect({});
    this.port.onMessage((data) => {
      this,update(data);
    });
  },
  update(data) {
    this.callbacks.forEach((callback) => {
      callback(data);
    });
  },
  register(callback) {
    this.callbacks.add(callback);
  }
}
```

**Comment by jonathanKingston** [comment]
Ideally the above can use `browser.runtime.sendMessage()` instead of `connect` and `onConnect`

**Comment by jonathanKingston** [comment]
The thing to note is that perhaps we shouldn't always fire the callback on `setFirstParty` and `setThirdParty` and instead just update when a new sites or links are added to the store. This would make the callback way less coupled to the shape stored in the storage too.

Lets discuss what that might look like however getting the above working first would be probably a quick easy step, then we can worry about how the messaging becomes less crazy.
