### ISSUE TITLE
Consider dropping third parties with only one connection

### ISSUE THREAD

**Issue by jonathanKingston** [electrolyfish/lightbeam-we#89]
When sites with lots of third parties are drawn it can clutter the graph. Third parties that never link to another first party is basically just part of the first party usually.

This makes domains like google.com have 100s of third parties without connections and I am fairly certain the existing graph just hides these nodes until they are shared with another first party.

**Comment by biancadanforth** [comment]
Closing this issue and replacing it with Issue #98 .
