### ISSUE TITLE
Use the Disconnect Entity List to whitelist first-party-owned third parties

### ISSUE THREAD

**Issue by biancadanforth** [electrolyfish/lightbeam-we#98]
Some websites (like fastcompany.com, below) can link to literally dozens or even hundreds third parties, creating a subgraph in the visualization that is very cluttered. Not all of these third parties are malicious trackers.

![fastcompany.com and its third parties](https://user-images.githubusercontent.com/17437436/28078840-033db5e0-661b-11e7-9f62-f09b48b56255.png)

We had originally created Issue #89 to declutter the graph by removing third parties that never link to more than one first party; however, these third parties could still pose a threat by [fingerprinting](http://spectrum.ieee.org/computing/software/browser-fingerprinting-and-the-onlinetracking-arms-race) via back-end data sharing, where the same tracker operates a number of different domains to stay off of tracker blacklists.

We can use the [Disconnect Entity List](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-entitylist.json) used by Firefox's Tracking Protection tool. In order to ensure we are using the most up-to-date version of this list, we should use the Disconnect Entity List repository as a submodule.

@groovecoder , if there are any additional helpful details or links (perhaps about back-end data sharing or using submodules), please add them below!

**Comment by biancadanforth** [comment]
The problem (paraphrasing @jonathanKingston ):
When I visit https://developer.mozilla.org/en-US/docs/Tools/Web_Console, I only see two third party nodes, when I know it should have more (like nine) on the visualization. This problem was found in this PR and absent in @princiya 's latest PR. It must be related to the whitelist code.

The solution:
Actually, it's not! All 30+ third party requests were correctly being passed into `store.js` from `capture.js`, so I had to look inside `store.js` to find the problem. Funnily enough, `store.js` wasn't touched at all in this PR.

Why would you see this problem in my PR and not in Princiya's? My guess is that you visited the [MDN site](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) using Lightbeam with no prior data in storage, then without resetting the data, ran Princiya's PR; this would mask the problem while falsely suggesting there was a problem in the whitelist code. Let me explain...

When Lightbeam is first opened or the data is reset, `this._websites` is set to `null`. It remains `null` until the first time the asynch method `store.setWebsite` is called. This is problematic, because before `store.setWebsite` is called, the synch method `store.getWebsite` is called (current method found [here](https://github.com/biancadanforth/lightbeam-we/blob/8a1b4ba00cc629f708f8c519cb1f55cf0436e030/js/store.js#L76), but pasted below).

```javascript
getWebsite(hostname) {
    if (!hostname) {
      throw new Error('getWebsite requires a valid hostname argument');
    }

    return this._websites[hostname];
},
```

When `this._websites` is `null`, as is the case when Lightbeam is run for the first time or the data is reset, we are trying to access a key on `null`. This would silently fail (@jonathanKingston, @groovecoder any ideas why no error would be thrown?) until the first call to the asynch method `setWebsite` returned and `this._websites` was no longer `null`.

The fix is to modify the `store.getWebsite` method to not only check if the `hostname` key exists, but also if `this._websites` is `null`, so that an empty object is returned in that case, which was previously unaccounted for.

```javascript
  getWebsite(hostname) {
    if (!hostname) {
      throw new Error('getWebsite requires a valid hostname argument');
    }
 
    if (this._websites && this._websites[hostname]) {
      return this._websites[hostname];
    } else {
      return {};
    }
  },
```
An ancillary thought:
Until the first time `store.setWebsite` is called with this updated code, `store.getWebsite` will always return `{}`. This could cause `store.updateChild` inside of `store.setThirdParty` to get called a few extra times (related issue #105 ).

@jonathanKingston , Why do we initialize `this._websites` to null, instead of `{}` to begin with?

Submitting the change to `store.getWebsite` forthwith!

**Comment by jonathanKingston** [comment]
> @jonathanKingston , Why do we initialize this._websites to null, instead of {} to begin with?

Can't remember. This seems like a decent solution for now though if that is the cause. Will check the PR. Thanks for dragging yourself through this.
